### ISSUE TITLE
automation error: The 'main' provisioner could not be found.

### ISSUE THREAD

**Issue by abelsonlive** [newslynx/opportunities#100]
![screenshot 2015-08-31 15 18 28](https://cloud.githubusercontent.com/assets/1621721/9588024/c9d7cbd6-4ff3-11e5-9ebc-d7ddf6c0f68b.png)

Getting this error when i try to run `make init_vb`

**Comment by mhkeller** [comment]
Hmm, i just ran it and it worked okay for me. what happens when you run `vagrant up --no-provision`

![screen shot 2015-08-31 at 15 26 26 pm](https://cloud.githubusercontent.com/assets/498744/9588134/8f5a135a-4ff4-11e5-9472-2fbbd93b9672.png)

**Comment by abelsonlive** [comment]
same thing.

**Comment by mhkeller** [comment]
What version of vagrant are you running

**Comment by mhkeller** [comment]
I think the provision commands are as of 1.7

**Comment by abelsonlive** [comment]
yeah that's prolly it, let me test.

**Comment by mhkeller** [comment]
I'll add a note in the readme and have the make file print the version for easy reference.

**Comment by mhkeller** [comment]
https://github.com/newslynx/automation/commit/34add2e0edf84fa6326e9bc1aeeda96e880bfd0b
