### ISSUE TITLE
How to force rerun recipes?

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#121]
GA sous chef has been updated and `make update` reran on automation but the last run on those recipes is still 9 days ago. How do you force rerun of a recipe?

TODO fill in docs: http://newslynx.readthedocs.org/en/latest/recipes.html

**Comment by mhkeller** [comment]
Edit: last run ran at the appropriate time, was reading wrong field. but would still like to force rerun.

**Comment by abelsonlive** [comment]
GET `/api/v1/recipes/:recipe_id/cook`

**Comment by abelsonlive** [comment]
or, via the cli:

```
$ newslynx api recipes cook id=<recipe_id>
```

**Comment by mhkeller** [comment]
thanks!

**Comment by abelsonlive** [comment]
FYI: this is in the docs for every sous chef module, IE: http://newslynx-sc-google-analytics.readthedocs.org/en/latest/sous-chefs.html#recipes

**Comment by mhkeller** [comment]
Thanks. A few other command line commands are throughout the newslynx docs. i can take a first pass at adding them to http://newslynx.readthedocs.org/en/latest/cli.html

**Comment by abelsonlive** [comment]
there are standard cli help menus via `newslynx api --help`
