### ISSUE TITLE
Some metric comparison fields negative min

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#125]
![screen shot 2015-09-12 at 06 51 21 am](https://cloud.githubusercontent.com/assets/498744/9827197/dbbbc994-591a-11e5-9f33-8d3e7f223482.png)
![screen shot 2015-09-12 at 06 51 55 am](https://cloud.githubusercontent.com/assets/498744/9827198/dbe133aa-591a-11e5-8ae8-b039a352469e.png)
![screen shot 2015-09-12 at 06 51 04 am](https://cloud.githubusercontent.com/assets/498744/9827199/dc1301dc-591a-11e5-812b-277b3190aaca.png)

**Comment by mhkeller** [comment]
will check on this after refreshing finishes

**Comment by mhkeller** [comment]
Refreshing fixed it.

**Comment by abelsonlive** [comment]
I'm still getting them. It looks like there were just two bad articles from migration. You can find them with this query:

``` sql
   select * 
   from content_metric_summary 
   where content_item_id in (
       select content_item_id from (
           select content_item_id, (metrics->>'ga_exits')::numeric as ga_exits 
           from content_metric_summary  
           where org_id=2
       ) t
      where ga_exits < 0
    );
```

**Comment by abelsonlive** [comment]
as you can see, the `per_2_5` field is still positive:

![screenshot 2015-09-11 18 23 19](https://cloud.githubusercontent.com/assets/1621721/9827657/4487fb6e-58b2-11e5-9928-1147ff22ff66.png)

**Comment by mhkeller** [comment]
if they aren't like that in GA, wouldn't the refresh take care of it?

On Sat, Sep 12, 2015 at 7:23 AM, Brian Abelson notifications@github.com
wrote:

> as you can see, the per_2_5 field is still positive:
> 
> [image: screenshot 2015-09-11 18 23 19]
> https://cloud.githubusercontent.com/assets/1621721/9827657/4487fb6e-58b2-11e5-9928-1147ff22ff66.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/125#issuecomment-139675657
> .

## 

@mhkeller
mhkeller.com

**Comment by abelsonlive** [comment]
my thought was that it was bad data from the prototype that hadn't been overwritten.

**Comment by mhkeller** [comment]
k, i might delete those content items and re-add them manually
