### ISSUE TITLE
config question re: multiple organizations

### ISSUE THREAD

**Issue by aschweigert** [newslynx/opportunities#134]
So, trying to add a bunch of organizations and users to a single instance of newslynx...it's unclear whether in config.yml the Twitter, GA and Facebook API keys and such are shared for all of the organizations or if there's some way to set it up for each organization. Do we just create a FB/Twitter/GA app once and then for each organization they'll have the option to add their own via the dashboard? or does each organization need to create their own apps/API keys/etc. and then we add them to the config file somehow? Any docs on this that I'm missing?

**Comment by mhkeller** [comment]
The docs for that are [here](http://newslynx.readthedocs.org/en/latest/config.html#api-credentials) but the general idea, which I can add to them, is that the user gives their GA / Twitter / FB credentials to a GA / Twitter / FB app that you have created. So the config.yaml credentials are for your GA / Twitter / FB developer accounts, which organizations then authenticate against from [within the settings page](https://raw.githubusercontent.com/newslynx/user-manual/master/assets/newslynx-pages-02.png).

**Comment by mhkeller** [comment]
Added this explanation to the docs https://github.com/newslynx/docs/commit/0faae6d7b6a6a2c493f0fb719611c410d80be718
