### ISSUE TITLE
Error notifications for recipes.

### ISSUE THREAD

**Issue by abelsonlive** [newslynx/opportunities#137]
Recipes which fail should send out notifications with tracebacks. Ideally these should be somewhat configurable, so you could choose Slack / Email / etc.
RE: #136

**Comment by abelsonlive** [comment]
This is deployed and tested on production. We now have recipes logging errors to #notifcations in the NewsLynx slack account.

**Comment by abelsonlive** [comment]
Docs are here:
http://newslynx.readthedocs.org/en/latest/config.html#notifications

**Comment by mhkeller** [comment]
awesome!

On Tue, Oct 6, 2015 at 9:36 PM, Brian Abelson notifications@github.com
wrote:

> Docs are here:
> http://newslynx.readthedocs.org/en/latest/config.html#notifications
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/137#issuecomment-146053096
> .

## 

@mhkeller
mhkeller.com
