### ISSUE TITLE
Merlynne potion body color should be white

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#141]
Her body and half her face is blue but should probably be white. What do you think @ClariiD?

![screen shot 2015-09-26 at 11 23 45 am](https://cloud.githubusercontent.com/assets/498744/10119091/07db2b4c-6441-11e5-9e7d-020d9490d4f3.png)

**Comment by ClariiD** [comment]
this is an older version and was updated September 22, 2014 (see email), was also fixed for the measuring GIF.  attaching both here in case :)

![merlynnemagicpotions](https://cloud.githubusercontent.com/assets/2502178/10151999/5fedd4a2-661b-11e5-858d-ad1a36fe96eb.gif)
![merlynnemeasure](https://cloud.githubusercontent.com/assets/2502178/10152000/5fee6584-661b-11e5-89dd-3f16a3644db9.gif)

**Comment by mhkeller** [comment]
Thank you!
