### ISSUE TITLE
Add color gradient to impact tags

### ISSUE THREAD

**Issue by laurenfuhrmann** [newslynx/opportunities#149]
Have impact tag colors fade to white.

**Comment by mhkeller** [comment]
Added a bunch more and the ability to set custom colors via the color wheel and hex. I tried it going one step closer to white but they all got pretty indistinguishable at that point. 

![screen shot 2015-10-03 at 00 34 32 am](https://cloud.githubusercontent.com/assets/498744/10261455/af930830-6966-11e5-9361-aaab9650514a.png)

@laurenfuhrmann I'll leave this open to see how these work out over the next week or so. Also, if you have a default color set to make them go by category or level, we should put that in to the defaults.
