### ISSUE TITLE
New features for article page

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#153]
So I'm putting together the article export button and changing the metric columns. @laurenfuhrmann, what do you think of this layout / button text / button icons? 

![screen shot 2015-10-03 at 00 52 05 am](https://cloud.githubusercontent.com/assets/498744/10261503/1237f7a0-6969-11e5-87a5-2ce6d1ca25a5.png)

**Comment by laurenfuhrmann** [comment]
Looks great!

**Comment by mhkeller** [comment]
Cool. This is done in 1.2.0.
