### ISSUE TITLE
Requested URL error returns the requested URL

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#155]
Could the 404 message return the URL that was requested? It would help in a great deal in debugging

**Comment by abelsonlive** [comment]
404's are handled by `flask`. Not sure how to override it's error messages. What is the difference between the API returning the URL requested and logging the URL that you are requesting?

**Comment by mhkeller** [comment]
The benefit would be people getting a 404 could paste the result of their console output to help quickly trace what the problem with the request was instead of logging into the server and matching up the timestamps.

**Comment by abelsonlive** [comment]
That seems like a problem with the app's logging and not the api's error message. if the api returns a 404, then the app has made a mistake. perhaps you should catch errors and log the request to the console.

**Comment by mhkeller** [comment]
will all errors and only errors return an object with at `status` field? I currently log errors but this format comes back as an ok request.

**Comment by abelsonlive** [comment]
is it not coming back with a `status_code` of 404?

**Comment by abelsonlive** [comment]
going to close this for now.
