### ISSUE TITLE
Bring back "time on homepage" metric sous chef

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#157]

**Comment by abelsonlive** [comment]
should this have a default recipe @mhkeller ?

**Comment by mhkeller** [comment]
ya that would make sense with the other promotion style recipe / sous
chefs. it can get initialized it on the settings page once they fill out
the home page element similar to how the twitter lists and fb pages post to
their respective recipes.

On Tue, Oct 6, 2015 at 5:23 PM, Brian Abelson notifications@github.com
wrote:

> should this have a default recipe @mhkeller https://github.com/mhkeller
> ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/157#issuecomment-146006143
> .

## 

@mhkeller
mhkeller.com

**Comment by abelsonlive** [comment]
This is finished.
- sous chef module + docs: https://github.com/newslynx/newslynx-sc-homepage
- underlying python module + docs: https://github.com/newslynx/pageone
- new default recipe: https://github.com/newslynx/newslynx-core/blob/master/newslynx/app/defaults/recipes.yaml#L51
- added phantomjs role to automation: https://github.com/newslynx/automation/blob/master/provisioning/phantomjs.yaml

let me know if you have problems deploying via new issues.

**Comment by mhkeller** [comment]
Thanks!

On Tue, Oct 6, 2015 at 6:00 PM, Brian Abelson notifications@github.com
wrote:

> Closed #157 https://github.com/newslynx/opportunities/issues/157.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/157#event-428512541.

## 

@mhkeller
mhkeller.com
