### ISSUE TITLE
Re-enable GA visualizations

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#16]
Todo once api is finished

**Comment by abelsonlive** [comment]
If you pull `master`, `newslynx dev gen-random-data` will include the following summary-level metrics for content items

``` json
{
    "facebook_comments": 557,
    "total_events": 4,
    "total_event_tags": 4,
    "institution_level_events": 1,
    "facebook_likes": 53,
    "ga_entrances": 51513,
    "pinterest_shares": 594,
    "citation_category_events": 3,
    "reddit_downvotes": 688,
    "ga_pageviews_tablet": 794,
    "individual_level_events": 0,
    "linkedin_shares": 476,
    "promotion_category_events": 0,
    "other_category_events": 0,
    "googleplus_shares": 62,
    "media_level_events": 3,
    "ga_avg_time_on_page": 2.6054107585667157,
    "internal_level_events": 0,
    "ga_total_time_on_page": 54864,
    "reddit_upvotes": 390,
    "ga_pageviews_mobile": 326,
    "ga_pageviews": 50347,
    "twitter_shares": 994,
    "ga_pageviews_by_domain": [
        {
            "facet": "google.com",
            "value": 14
        },
        {
            "facet": "twitter.com",
            "value": 987
        },
        {
            "facet": "facebook.com",
            "value": 275
        }
    ],
    "change_category_events": 1,
    "ga_per_external": 2.535940895833605,
    "ga_exits": 46913,
    "community_level_events": 0,
    "achievement_category_events": 0,
    "facebook_shares": 604
}
```

**Comment by abelsonlive** [comment]
so there are `ga_pageviews_tablet`, `ga_pageviews_desktop` and `ga_pageviews_mobile` which would power the device visualization and `ga_pageviews_by_domain` which is a faceted metric and would power the domain facets.  

The former will have corresponding keys in the comparisons object while the latter (as with all faceted metrics, will not).

**Comment by mhkeller** [comment]
Here's a shot of what we had before for reference:

![screen shot 2015-07-12 at 18 04 26 pm](https://cloud.githubusercontent.com/assets/498744/8640282/850cc754-28c0-11e5-9c47-ed81ec32da6c.png)

trackbacks still TBD

**Comment by mhkeller** [comment]
This is mostly done. Depends on https://github.com/newslynx/opportunities/issues/48 and https://github.com/newslynx/opportunities/issues/47

As well as trackbacks "What articles link here?"

**Comment by abelsonlive** [comment]
I fixed the bug but the random data gen wont necessarily return numbers between 0 and 1. is there a problem with that?

**Comment by mhkeller** [comment]
It would be good if the random data gen did give realistic data so 1) we could use it for demo and 2) detect errors in the code. If the underlying data isn't correct it will make it harder to debug things to know if they are displaying as they should.

**Comment by abelsonlive** [comment]
It's a lot to ask. It means setting up a simulation based off of realistic data (which i would need to collect first).  If you can hold off for a week or so I should have a deployed version with real data coming in.
