### ISSUE TITLE
Add backup-to-s3 to automation

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#163]
Of postgres. Once a day is probably good.

**Comment by mhkeller** [comment]
What do you think of this @abelsonlive http://s3-backups.readthedocs.org/en/latest/

**Comment by abelsonlive** [comment]
this was closed via: https://github.com/newslynx/automation/commit/19ecbf09d801891fb46197f005e5ebbb2eea0a28

tested on aws server + deployed in production.
