### ISSUE TITLE
properly mount separate db drive

### ISSUE THREAD

**Issue by abelsonlive** [newslynx/opportunities#165]
currently only mounting one

**Comment by abelsonlive** [comment]
you'll need to redeploy to have this reflected in production @mhkeller

**Comment by mhkeller** [comment]
cool.

On Tue, Oct 6, 2015 at 4:07 PM, Brian Abelson notifications@github.com
wrote:

> you'll need to redeploy to have this reflected in production @mhkeller
> https://github.com/mhkeller
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/165#issuecomment-145982790
> .

## 

@mhkeller
mhkeller.com
