### ISSUE TITLE
Allow multiple instances to use same S3 bucket for backups?

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#168]
@abelsonlive what's the advantage to setting it up as one s3 bucket per instance vs something like setting a string in `config.yaml` as something like `s3_backup_group` and constructing the `s3cmd` put command to something like `s3://{{conf.s3_bucket}}/backups/{{conf.s3_backup_group}}/`

**Comment by mhkeller** [comment]
On restore-backup branch the changes are

https://github.com/newslynx/automation/commit/9a540d48cb84e2c1fdf348227d24d7eb28d67ab5#diff-5575782dd113fd040f4b49ec3898f238R9

and here: 
 https://github.com/newslynx/automation/commit/9a540d48cb84e2c1fdf348227d24d7eb28d67ab5#diff-4f0e17ca799f63e1b2d7dbc656c4ee97R30

If there aren't unforeseen problems I can merge to master

**Comment by abelsonlive** [comment]
Yeah, that's a good idea. Looks fine to me.

**Comment by mhkeller** [comment]
Merged to master
