### ISSUE TITLE
Suitable automation admin commands?

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#171]
@abelsonlive does this cover everything to simply restart all processes? https://github.com/newslynx/automation/blob/master/provisioning/restart.yaml

**Comment by mhkeller** [comment]
I've added `stop`, `start` as well:

https://github.com/newslynx/automation/blob/restore-backup/provisioning/start.yaml
https://github.com/newslynx/automation/blob/restore-backup/provisioning/stop.yaml

**Comment by abelsonlive** [comment]
Yep that looks good. `start` seems unnecessary since `restart` does the same thing.

**Comment by mhkeller** [comment]
for the app, the `forever` command will fail if that forever process isn't
currently running so it uses the `forever start-automation`. i was thinking
similarly and then i ran into that little bug.

On Mon, Oct 12, 2015 at 4:38 PM, Brian Abelson notifications@github.com
wrote:

> Yep that looks good. start seems unnecessary since restart does the same
> thing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/171#issuecomment-147513325
> .

## 

@mhkeller
mhkeller.com
