### ISSUE TITLE
What's the proper sous chef update pattern

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#174]
Related to https://github.com/newslynx/opportunities/issues/173

If we change https://github.com/newslynx/newslynx-sc-google-analytics/blob/d5a725f25f5e5d34339081f5d852feeca80c34cd/newslynx_sc_google_analytics/__init__.py#L24 to something greater, what would be required to update the instance? Manually pulling that repo and running `make restart`?

**Comment by abelsonlive** [comment]
As per the documentation in every Sous Chef module, you just run `newslynx sc-sync` which does the following:
1. Pull all repos
2. Reinstall the Sous Chef modules.

You don't need to restart the API since these modules will be called at run time.

**Comment by mhkeller** [comment]
I increased the timeout and ran `newslynx sc-sync` and i got only this output. Looking at the `git log` for `newslynx-sc-google-analytics`, however, it has pulled the latest. So, it seems that it did pull all repos but only reported that it pulled the rss repo.

```
$ newslynx sc-sync
19:53:23 | newslynx.sc.sc_sync-25 | Updating all Sous Chef Modules
19:53:23 | newslynx.sc.sc_module-188 | Pulling latest version of "/root/.newslynx/sous-chefs/newslynx-sc-rss"
$
```

**Comment by abelsonlive** [comment]
yeah theres some bug in the logging there on ubuntu machines. not sure what
it is.

On Saturday, October 17, 2015, Michael Keller notifications@github.com
wrote:

> I increased the timeout and ran newslynx sc-sync and i got only this
> output. Looking at the git log for newslynx-sc-google-analytics, however,
> it has pulled the latest. So, it seems that it did pull all repos but only
> reported that it pulled the rss repo.
> 
> $ newslynx sc-sync
> 19:53:23 | newslynx.sc.sc_sync-25 | Updating all Sous Chef Modules
> 19:53:23 | newslynx.sc.sc_module-188 | Pulling latest version of "/root/.newslynx/sous-chefs/newslynx-sc-rss"
> $
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/174#issuecomment-148947704
> .

## 

## 

i = 'brianabelson'
@i http://www.twitter.com/brianabelson
i.org http://brianabelson.org

**Comment by abelsonlive** [comment]
closing in favor of more specific issue
