### ISSUE TITLE
Metrics endpoint returns metrics from other orgs

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#177]
The `org` filter doesn't seem to work on the `/metrics` endpoint. It returns metrics from other organizations.

**Comment by abelsonlive** [comment]
The issue is that since these tweets are being collected as-they-are tweeted, I'm not getting historical ones (when the collection was not taking place).  If you looked more closely at those tweets you linked to, you'll see that the most recent one was from September 22nd.
