### ISSUE TITLE
Allow POSTing to `/me/settings/:setting-name`

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#178]
Would POSTing a new setting to the setting slug that it will have make sense within the current design? The reason where this would make things easier so you could create a model on the client that has a stable URL of `/me/settings/my-setting` when it is created and then is subsequently updated.

**Comment by abelsonlive** [comment]
Nah, that doesn't really follow RESTFul design.

**Comment by mhkeller** [comment]
Bumma.
