### ISSUE TITLE
Add ability to GET content_items by id

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#23]
It would be helpful to filter by content item ids. This is used in the comparison field for permalinks so you can load up a custom selection of articles by id.

**Comment by abelsonlive** [comment]
Would the same apply for events as well?

**Comment by mhkeller** [comment]
Currently the interface doesn't have that feature so I would say it's not needed. The closest the interface comes is when it plots events in the rows below the chart but I don't see why I couldn't store the full event data on that dot and return it on any click / hover interaction. If you want to implement it for consistency reasons that would be fine.

**Comment by abelsonlive** [comment]
I implemented this for `content` and `events`.  The docs have been updated as well. 

The following parameters have been added:

`ids` -  a comma-separated list of ids to filter by. 
`sort_ids` - whether or not to use the order of these ids to sort the results by.

https://github.com/newslynx/newslynx-core/commit/5503743f476761532caa906afa53e5b5ae2d77e7
