### ISSUE TITLE
Nulls in timeseries?

### ISSUE THREAD

**Issue by abelsonlive** [newslynx/opportunities#43]
How would nulls affect the timeseries visualization?  

Computed metrics might sometimes be null in the case there is division by zero -- I could simply make these zero, but i wonder if there might be certain metrics where 0 means something completely different and equating the two would render summaries + comparisons invalid

**Comment by abelsonlive** [comment]
btw: i just pushed better random data gen which removes nulls so you can push this off for a bit.

**Comment by mhkeller** [comment]
What would an example be? Maybe a break in the line would be more accurate than zero so simply no value. That would only make sense for a non-sparse format, though. Is this just for timeseries metrics?

**Comment by abelsonlive** [comment]
It would only be for _computed_ timeseries metrics.  The examples are fairly specific to cases where either the user requests non-sparse data (which fills in 0s) or there are 0s in the timeseries, and these 0s end up as the denominator in an equation. (`ga_per_external`, `ga_avg_time_on_page`)

**Comment by mhkeller** [comment]
I think keeping these as `null` would be best. The chart drawing logic could draw a break in the line instead of a drop to `0`.
