### ISSUE TITLE
Opportunity schema?

### ISSUE THREAD

**Issue by abelsonlive** [newslynx/opportunities#44]
Was thinking it might be nice if we were more explicit about the issues we create so that if people were interested in contributing they might understand what would need to be modified in order to add a new feature. What do you think?

**Comment by abelsonlive** [comment]
Something like every issue should always have a:
- Description
- Links to files/functions/classes involved.
- Estimation of effort required.

**Comment by mhkeller** [comment]
Sounds good. We could create different tags for scale of effort required. Similar to how california civic data coalition has small medium and large tags https://github.com/california-civic-data-coalition/django-calaccess-campaign-browser/issues
