### ISSUE TITLE
Allow user-specific comparison grid display

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#46]
Currently, elements like `title`, `created` and various metrics, as well as subject and impact tags are referred to as "dimensions" and are displayed in the comparison grid. This list is defined in the dimensions model here: https://github.com/newslynx/newslynx-app/blob/v2/lib/public/javascripts/collections/dimensions.js#L8-L36

It would be great if a user could alter this list **just** for their account. A user setting of `dimensions` would be scaffolded on initialization and could be altered by POSTing changes.

**Comment by abelsonlive** [comment]
you could leverage the `org-settings` API for this, which accepts any `json`.  I guess the potential limitation here is that it would then be org-specific and not user-specific.

**Comment by mhkeller** [comment]
Ya, if there was a similar any json user settings, this would be fairly easy.

**Comment by abelsonlive** [comment]
I've modified the settings API to handle both user and organization-specific settings.  You will have to change your existing calls to the settings API to be prefaced with `orgs`, for instance:

`/api/v1/settings/timezone` => `/api/v1/orgs/settings/timezone` 

You can now manage user-level settings at the following endpoint:

`/api/me/settings/:setting_name`.  

This only allows modifiying settings for the authenticated user (determined by the `apikey` passed in).  This means that you shouldn't have to fuss too much about figuring out which settings are associated with which users, it should just work.

These changes are reflected in the docs: 
http://newslynx.readthedocs.org/en/latest/api.html#settings

**Comment by mhkeller** [comment]
This is implemented in 1.2.0.
