### ISSUE TITLE
`ga_per_external` not calculated correctly

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#47]
@abelsonlive this a by-product of random data gen?
![screen shot 2015-07-13 at 22 38 41 pm](https://cloud.githubusercontent.com/assets/498744/8665273/0797cec2-29b0-11e5-9b2c-d6f088175942.png)

**Comment by abelsonlive** [comment]
well i would say yes, but that also doesn't seem like it's computing the formula properly.

```
formula: '{ga_entrances} / NULLIF({ga_pageviews}, 0)'
```
