### ISSUE TITLE
All tweets per article

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#50]
Bring back the all tweets per article sorted by follower count. Should also be paginated.

**Comment by abelsonlive** [comment]
This will just be an `event` linked to a specific `recipe`.

**Comment by mhkeller** [comment]
For the other built-in recipes around promotion, the way I'm grabbing them is through a specific name, what should we call this recipe? I take it would filter events in this recipe by `content_item_id` or does each article have its own recipe?

**Comment by abelsonlive** [comment]
it will be a twitter search for an org's domains and short domains that utilize's the event-creation api's `must_link` flag.

**Comment by abelsonlive** [comment]
something like `twitter-search-domains-to-event-must-link` ?

**Comment by abelsonlive** [comment]
actually. this is going to be a particular sous-chef, so you could query for events that were created by the SousChef: `twitter-search-content-items-to-event`. this is much cleaner.

**Comment by abelsonlive** [comment]
You're only using the embed html for this view, correct?

**Comment by mhkeller** [comment]
correct just the embed. im loading the twitter js so whatever their
prescribed embed format is what ill use as opposed to reconstructing our
own cards.

i'm using the recipe name since using the sous-chef would be give me any
other events someone might make with that sous-chef. going off the recipe
is more specific.

On Tue, Jul 14, 2015 at 2:07 AM, Brian Abelson notifications@github.com
wrote:

> Your only using the embed html for this view, correct?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/50#issuecomment-121140201
> .

## 

@mhkeller
mhkeller.com

**Comment by mhkeller** [comment]
should we add this as a default recipe in the same way we're doing the others? lmk when to pull and rebuild to test

**Comment by mhkeller** [comment]
Finished in app: 
https://github.com/newslynx/newslynx-app/commit/7448bb5e317aef4fc630f7d080a16f7f4a8681c9 
https://github.com/newslynx/newslynx-app/commit/7a0b836afedae9d37a8b0dc42ef0630baa1e8dd5 
https://github.com/newslynx/newslynx-app/commit/833ceb5bd61ab249a7afc836edc5e6ef5f7b44f8

needs [`meta.embed`](https://github.com/newslynx/newslynx-app/commit/833ceb5bd61ab249a7afc836edc5e6ef5f7b44f8#diff-cc0705269a2430fc3325665ae133544cR29) in events
