### ISSUE TITLE
Save / load config from `Application Suppor` or create `.newslynx` file for Electron environment

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#54]
The Electron app should be as self-contained as possible but it does need to have a config.yaml somewhere to edit. Related to https://github.com/newslynx/opportunities/issues/32

**Comment by abelsonlive** [comment]
Are `env` variables an option? I'm using `NEWSLYNX_APIKEY`, `NEWSLYNX_ORG` and `NEWSLYNX_URL` for the api client.

**Comment by mhkeller** [comment]
[I was using that](https://github.com/newslynx/newslynx-electron/blob/master/package.json#L19), which works locally but when it builds the app, it doesn't say "Run this always with an env variable." I was using that to look for the `config.yaml`in the `newslynx-electron` root folder instead of `~/.newslynx` https://github.com/newslynx/newslynx-app/blob/v2/lib/settings/config.js#L8-L9.

The issue goes beyond that, though, I discovered, which is that folder is not really is a logical place to put this config file since when it gets packaged, it's not easy to find that package. I guess it could store it somehow in the LevelDB store as opposed to the config.yaml, but setting up these different ways of loading config variables needs more thinking. I think loading it as a node module is the best way, since npm has its own logic for keeping track of data data.

**Comment by mhkeller** [comment]
I ended up setting this config as a manually added node_module, which delegates to require and require.resolve to figure out where it is: https://github.com/newslynx/newslynx-electron/commit/b351e549602a103910b911964c5e4f45beb91b01
