### ISSUE TITLE
SSL 3 Errors

### ISSUE THREAD

**Issue by abelsonlive** [newslynx/opportunities#55]
Some of my `requests` to the web are failing because of ssl3 errors. not sure if this is specific to my local machine or a general issue.

```
WARNING:newslynx.lib.network:Exception - [Errno bad handshake] [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')] on try 2 for ('https://badgerherald.com/news/2015/07/12/walker-vetoes-104-items-from-2015-17-biennial-budget/',)
```

might need to do something like this: 
https://lukasa.co.uk/2013/01/Choosing_SSL_Version_In_Requests/

The relevant code is encapsulated here:
https://github.com/newslynx/newslynx-core/blob/master/newslynx/lib/network.py#L111

**Comment by abelsonlive** [comment]
Seems like it might be related to mac os x's default SSL version: https://github.com/kennethreitz/requests/issues/2022

**Comment by mhkeller** [comment]
@abelsonlive was this a websites certificate being out of date or something we should keep open?
