### ISSUE TITLE
Create `newslynx-docs` repo

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#61]
@abelsonlive I'm thinking we break the stuff on Read the Docs into its own repo so I can add any of the front-end and express material in there without having to change the `newslynx-core` files.

**Comment by abelsonlive** [comment]
yeah sounds good.

**Comment by mhkeller** [comment]
I've switched it. When I added the webhook I thought it would ask me for credentials but it didn't. How do you tell it where to build on readthedocs.org? Or is that in the configuration somewhere?

**Comment by mhkeller** [comment]
Or if it's set up through their site's interface, add the credentials to the share and ill change.

**Comment by abelsonlive** [comment]
yeah i have it under my personal account. i'll setup a new one. the only problem is that the url will be `newslynx-docs.readthedocs.org`. maybe we should just configure it to be `github-pages`. Then we can also set a custom domain.

**Comment by mhkeller** [comment]
could we rename the repo to be newslynx, then connect it to readthedocs.org, then rename the gh repo back to docs?

**Comment by mhkeller** [comment]
was that how we did it before?

**Comment by abelsonlive** [comment]
oh yeah that would work too i guess. i like the `gh-pages` option though. should be easy to configure. once i finish automation i'll try that.

**Comment by mhkeller** [comment]
one benefit of the rtd option is we wouldn't have to always be paying for a
custom domain

On Sun, Jul 19, 2015 at 11:52 PM, Brian Abelson notifications@github.com
wrote:

> oh yeah that would work too i guess. i like the gh-pages option though.
> should be easy to configure. once i finish automation i'll try that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/61#issuecomment-122751819
> .

## 

@mhkeller
mhkeller.com

**Comment by mhkeller** [comment]
@abelsonlive Can you switch the `docs` repo to point to `newslynx.readthedocs.org` via changing repo name until webhook settles etc.?

**Comment by mhkeller** [comment]
This is done
