### ISSUE TITLE
how to configure the app's "host"

### ISSUE THREAD

**Issue by abelsonlive** [newslynx/opportunities#64]
In order to automate the app deployment, i need to be able to set the `host` as something other than `127.0.0.1`. What's the best way to do this?

**Comment by mhkeller** [comment]
https://github.com/newslynx/newslynx-app/commit/6243cb5e1dd98869173aa62ff79e50655a36617d#diff-f5b348ab6a142742be9a5df94cfba8fdR38

**Comment by mhkeller** [comment]
I also added it as an env variable if you want `NEWSLYNX_HTTP_HOST`

**Comment by abelsonlive** [comment]
thanks!
