### ISSUE TITLE
exports

### ISSUE THREAD

**Issue by abelsonlive** [newslynx/opportunities#66]
I'm going to make the reports api handle exports. Reports are now going to execute Sous Chefs and cache the results. Eventually I'll set them up to archive previous versions.

You should expect to be able to do something like this:
##### GET``/ap1/v1/reports/:report_id_or_slug.:format?:sous_chef_options`
- Fetches a report. include `refresh` for a fresh copy. Use `csv.zip` for the format.
- So you might do something like `api/v1/reports/export-content.csv.zip?content_item_ids=1` for a single export and `api/v1/reports/export-content.csv.zip?content_item_ids=1,2,3,4,5` for a bulk export.

**Comment by mhkeller** [comment]
cool. check out the ykk docs for the response json format: https://github.com/newslynx/ykk#example-configuration

The list of desired data: https://github.com/newslynx/opportunities/issues/51

Current naming convention on those keys, which become file names

https://github.com/newslynx/newslynx-app/blob/v2/lib/public/javascripts/views/ArticleDetail.js#L261

``` js
var timestamp = now.format('YYYY-MM-DDTHH-mm');

// Subject tag csv
csvs[timestamp+'_article_'+this.model.id+'_subject_tags'] = model_json.subject_tags_full.map(addExportedDate)
// Impact tag csv
csvs[timestamp+'_article_'+this.model.id+'_impact_tags'] = model_json.impact_tags_full.map(addExportedDate)
```

I'm also adding an exported date to every row so you could cat these csvs 

https://github.com/newslynx/newslynx-app/blob/v2/lib/public/javascripts/views/ArticleDetail.js#L275-L280

**Comment by mhkeller** [comment]
For putting tags into a single cell, I'm doing 

```
4,foo_tag_name|2,bar_tag_name|5,baz_tag_name
```

And also supplying a vlookup-able spreadsheet listing all tag info with the associated content item id and exported date

**Comment by mhkeller** [comment]
Closing this for now as exports are being handled in Express
