### ISSUE TITLE
standardize app config variable naming?

### ISSUE THREAD

**Issue by abelsonlive** [newslynx/opportunities#68]
I've been trying to namespace all configs to stay organized, can we change the [app config vars](https://github.com/newslynx/newslynx-app#getting-started) to 

```
app_secret_key: chicken-burrito-grande
app_https: false
```

Also, i think you don't need to worry about ssh because that will be handled by nginx.

**Comment by mhkeller** [comment]
the `newslynx_` namespace would be good to keep in case there are multiple things

**Comment by mhkeller** [comment]
is `api_version` getting a prefix too?

**Comment by mhkeller** [comment]
for whether the app needs to know about it, there are some settings for cookies that are advised to be changed if running in that environment

**Comment by mhkeller** [comment]
we could assume that it is always running in https if not in dev and have it set that way if there isn't a way to communicate the https status to the app.

**Comment by mhkeller** [comment]
as in, you dont want to set env variables or change config.yaml

**Comment by abelsonlive** [comment]
closing for now since automation works.
