### ISSUE TITLE
Box suggestions

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#72]
Are there any loose guidelines we could add to the docs for people picking what kind of box to run everything on? Maybe using our prototype as a comparison

**Comment by abelsonlive** [comment]
I'd say a medium AWS instance should work for a single organization (Wisconsin Watch sized).  I'm not really sure how large of a box you would need for a Mother Jones / Vox sized newsroom.

**Comment by mhkeller** [comment]
Is there any separate provisioning for postgres to consider?

**Comment by abelsonlive** [comment]
i mean, i guess ideally you'd have everything on a separate box in a VPC. I don't really know how to automate a deployment like that though.
