### ISSUE TITLE
NotFoundError: This Org does not exist.

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#73]
In updating for https://github.com/newslynx/opportunities/issues/46, pulled latest, reinstalled and ran `newlynx dev gen_random_data` I'm getting the following. Has dummy org generation been changed? 

```
INFO:werkzeug:127.0.0.1 - - [26/Jul/2015 21:46:43] "GET /api/v1/me?apikey=mj&org=1 HTTP/1.1" 200 -
ERROR:newslynx.core:Exception on /api/v1/orgs/settings [GET]
Traceback (most recent call last):
  File "/Users/mike/.virtualenvs/nl/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mike/.virtualenvs/nl/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mike/.virtualenvs/nl/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mike/.virtualenvs/nl/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mike/.virtualenvs/nl/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/views/decorators.py", line 35, in decorated_function
    return f(*args, **kw)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/views/api/orgs_api.py", line 54, in org
    'This Org does not exist.')
NotFoundError: This Org does not exist.
```

This `http://localhost:5000/api/v1/orgs?apikey=mj&org=1` returns 

``` json
[

{

    "updated": "2015-07-26T21:03:06.192726-04:00",
    "name": "admin",
    "created": "2015-07-26T21:03:06.192706-04:00",
    "auths": { },
    "settings": { },
    "id": 1,
    "timezone": "UTC",
    "slug": "admin",
    "users": 

[

        {
            "updated": "2015-07-26T21:03:06.194842-04:00",
            "name": "Merlynne Jones",
            "created": "2015-07-26T21:03:06.189573-04:00",
            "admin": true,
            "super_user": true,
            "id": 1,
            "email": "merlynne@newslynx.org"
        }
    ]

},
{

    "updated": "2015-07-26T21:03:20.566098-04:00",
    "name": "Tubjing",
    "created": "2015-07-26T21:03:20.566075-04:00",
    "auths": { },
    "settings": { },
    "id": 2,
    "timezone": "America/New_York",
    "slug": "tubjing",
    "users": 

[

{

    "updated": "2015-07-26T21:03:06.194842-04:00",
    "name": "Merlynne Jones",
    "created": "2015-07-26T21:03:06.189573-04:00",
    "admin": true,
    "super_user": true,
    "id": 1,
    "email": "merlynne@newslynx.org"

},
{

    "updated": "2015-07-26T21:03:20.540239-04:00",
    "name": "Winnifred Ortiz",
    "created": "2015-07-21T13:03:20.522371-04:00",
    "admin": true,
    "super_user": false,
    "id": 2,
    "email": "modesto@example.com"

},

            {
                "updated": "2015-07-26T21:03:20.560462-04:00",
                "name": "Noble Zulauf",
                "created": "2015-07-24T05:03:20.543610-04:00",
                "admin": true,
                "super_user": false,
                "id": 3,
                "email": "brennon@example.com"
            }
        ]
    }

]
```

**Comment by abelsonlive** [comment]
yeah i think it's because i added a "SUPER_USER_ORG" for automation reasons so the account you're loggin in with is not linked to the random data generation. i'll look into it tonight.

**Comment by abelsonlive** [comment]
What do these tables look like for you? Here are mine:

`orgs`:

![screenshot 2015-07-30 11 32 40](https://cloud.githubusercontent.com/assets/1621721/8987402/ec215800-36ae-11e5-9bc2-888838f50b74.png)

`users`:

![screenshot 2015-07-30 11 32 50](https://cloud.githubusercontent.com/assets/1621721/8987410/f5e20d12-36ae-11e5-8e6b-8fbc9fbaf9c7.png)

`orgs_users`:

![screenshot 2015-07-30 11 32 58](https://cloud.githubusercontent.com/assets/1621721/8987418/faa30f54-36ae-11e5-9ae3-25076d015059.png)

**Comment by mhkeller** [comment]
![screen shot 2015-07-30 at 19 05 55 pm](https://cloud.githubusercontent.com/assets/498744/8997319/07f7cb9c-36ee-11e5-87cc-1cdd71464bbe.png)
![screen shot 2015-07-30 at 19 05 46 pm](https://cloud.githubusercontent.com/assets/498744/8997320/07f930cc-36ee-11e5-8afc-ebfee317e38d.png)
![screen shot 2015-07-30 at 19 05 50 pm](https://cloud.githubusercontent.com/assets/498744/8997318/07f65cbc-36ee-11e5-9915-fdb400b48737.png)

**Comment by mhkeller** [comment]
On the endpoint that's giving an error it's asking for [`'/api/v1/orgs/<org_id_slug>'`](https://github.com/newslynx/newslynx-core/blob/master/newslynx/views/api/orgs_api.py#L44) but per the endpoint change in https://github.com/newslynx/opportunities/issues/46#issuecomment-124728852, it's `/api/v1/orgs/settings` and `/api/v1/orgs/settings/timezone`. What is `<org_id_slug>` supposed to be?

**Comment by abelsonlive** [comment]
So I guess flask wasn't smart enough to distinguish those routes across multiple blueprints with asynchronous requests. I changed the orgs endpoint to only accept integer IDs and this fixed it. I tested it on the app.
