### ISSUE TITLE
automation fails with pg_config not in PATH

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#74]
```
Please add the directory containing pg_config to the PATH

or specify the full executable path with the option:

python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.
```

**Comment by mhkeller** [comment]
Possibly resolved by installing `libpq-dev`

**Comment by mhkeller** [comment]
http://stackoverflow.com/questions/11618898/pg-config-executable-not-found

**Comment by abelsonlive** [comment]
in what context are you running automation? the postgres role takes care of all this:

https://github.com/newslynx/automation/blob/master/provisioning/postgres.yaml#L2

**Comment by mhkeller** [comment]
This appears to be a virtualbox error
