### ISSUE TITLE
aws automation

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#75]
I've created a separate automation routine for skipping virtualbox and deploying to aws: https://github.com/newslynx/automation-aws

A few points:
1. It would be good if this were an option in one `automation` repo as opposed to a separate but identical anible playbook
2. It currently doesn't do the same provisioning for the `pg_mnt` but it does work
3. In `servers.json` in `automation`, there is an empty key for `aws`. Is there a simpler way to do this using that structure?

**Comment by abelsonlive** [comment]
Yes, vagrant has an aws plugin. Not sure how to automate the mounting of
the drive. We could also create a base AMI and then just have the
automation spin that up and run the playbook.

On Saturday, August 1, 2015, Michael Keller notifications@github.com
wrote:

> I've created a separate automation routine for skipping virtualbox and
> deploying to aws: https://github.com/newslynx/automation-aws
> 
> A few points:
> 1. It would be good if this were an option in one automation repo as
>    opposed to a separate but identical anible playbook
> 2. It currently doesn't do the same provisioning for the pg_mnt but it
>    does work
> 3. In servers.json in automation, there is an empty key for aws. Is
>    there a simpler way to do this using that structure?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/75.

## 

## 

i = 'brianabelson'
@i http://www.twitter.com/brianabelson
i.org http://brianabelson.org

**Comment by mhkeller** [comment]
The vagrant aws config has options for an EBS volume, is that an equivalent to what the virtualbox mounts: https://github.com/newslynx/automation-aws/blob/master/Vagrantfile#L28

The virtual box mounts at this path however https://github.com/newslynx/automation/blob/master/servers.json#L8, is that a specific location that other parts of the config will look to? The vagrant provisioning does some checks for whether it can mount pg and those seem to pass with the current aws setup.
