### ISSUE TITLE
Add updating the automation.

### ISSUE THREAD

**Issue by abelsonlive** [newslynx/opportunities#81]
The Automation scripts should include means for easily updating your version of `newslynx`. 

This should:
- clone the repos
- ensure the dependencies are installed
- restart the daemons.

**Comment by mhkeller** [comment]
For the app, the steps needed are:
1. pull the latest
2. npm install
3. restart forever daemon

@abelsonlive could you list which parts of the provision steps are needed and i can take a crack at implementing?

I'm guessing
1. checkout master https://github.com/newslynx/automation/blob/master/provisioning/newslynx-core.yaml#L23
2. pull https://github.com/newslynx/automation/blob/master/provisioning/newslynx-core.yaml#L29
3. install https://github.com/newslynx/automation/blob/master/provisioning/newslynx-core.yaml#L35
4. initialize https://github.com/newslynx/automation/blob/master/provisioning/newslynx-core.yaml#L72

**Comment by mhkeller** [comment]
WIP on this branch: https://github.com/newslynx/automation/tree/update

**Comment by mhkeller** [comment]
This is done
