### ISSUE TITLE
vagrant up --provider=aws

### ISSUE THREAD

**Issue by generalhash** [newslynx/opportunities#83]
issuing vagrant up --provider=aws    #produces:

root@(none):/home/ubuntu/.newslynx/automation-master# vagrant up --provider=aws
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

(<unknown>): mapping values are not allowed in this context at line 6 column 19

additional Info:
root@(none):/home/ubuntu/.newslynx/automation-master# head -6 config.yaml

<!DOCTYPE html>
<html lang="en" class=" is-copy-enabled">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">

**Comment by mhkeller** [comment]
Appears to be a problem with config.yaml that was converted into an html document by the server.

**Comment by mhkeller** [comment]
Investigating...

**Comment by mhkeller** [comment]
This was a problem with the amazon box. A fresh install fixed it.
