### ISSUE TITLE
automated install using AWS 

### ISSUE THREAD

**Issue by generalhash** [newslynx/opportunities#84]
Error: 
root@(none):/home/ubuntu/newslynx-automation# vagrant up --provider=aws
The provider 'aws' could not be found, but was requested to
back the machine 'newslynx'. Please use a provider that exists.

**Comment by mhkeller** [comment]
I'm thinking this is a problem with the plugin install. Try reinstalling that and if it gives the same problem.

**Comment by mhkeller** [comment]
An error on the amazon box was causing the plugin installation to fail. A fresh box fixed it.
