### ISSUE TITLE
Unversioned dependencies

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#87]
newslynx-core has a few unversioned dependencies, which seems like it could cause problems down the road: https://github.com/newslynx/newslynx-core/blob/master/requirements.txt

**Comment by abelsonlive** [comment]
https://github.com/newslynx/newslynx-core/commit/ada9cb01d66e4e04ef7f71d9447c35ab9bbbb28d

**Comment by mhkeller** [comment]
googleanalytics was unversioned as well as the rest of its dependencies: https://github.com/newslynx/newslynx-sc-google-analytics/blob/master/requirements.txt

None of these requirements files have version numbers meaning they are liable to break. 

https://github.com/newslynx/newslynx-sc-rss/blob/master/requirements.txt
https://github.com/newslynx/newslynx-sc-twitter/blob/master/requirements.txt
https://github.com/newslynx/newslynx-sc-shares/blob/master/requirements.txt
https://github.com/newslynx/newslynx-sc-reddit/blob/master/requirements.txt

@abelsonlive please add the current versions for these packages that you have tested / built with — with the exception of `newslynx` for now until it is at a stable release.

**Comment by mhkeller** [comment]
Some of these deps like googleanalytics are included in the newslynx core requirements.txt. they should be removed from there if the core library does not use them.
