### ISSUE TITLE
Getting empty comparison objects after gen random data

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#95]
Does this take a while to run or do i need to manually start workers?

![screen shot 2015-08-26 at 01 01 41 am](https://cloud.githubusercontent.com/assets/498744/9485890/e7ee9826-4b8d-11e5-9372-684a18d0e454.png)

**Comment by abelsonlive** [comment]
no, it should run on-demand. it seemed to work fine for me and when i ran migration, so i'm closing for now. will reopen if it happens again
