### ISSUE TITLE
CU box failing with SQLAlchemy error

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#97]
To export recipes we need to log in to the box. getting this error on login

```
sqlalchemy.exc.OperationalError
\n
\n

OperationalError: (OperationalError) FATAL: password authentication failed for user "newslynx"\nFATAL: password authentication failed for user "newslynx"\n None None\
```

**Comment by mhkeller** [comment]
```
\n
File \"/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py\",\n line 164,\n in connect
\n

conn = _connect(dsn, connection_factory=connection_factory, async=async)

\n
\n
```

\n

```
OperationalError: (OperationalError) FATAL: password authentication failed for user "newslynx"\nFATAL: password authentication failed for user "newslynx"\n None None
```

**Comment by abelsonlive** [comment]
you need to make sure to activate the environment. In the root dir - `~/newslynx` - run `source env.sh`

https://github.com/newslynx/newslynx-prototype#what-do-you-want-to-do

**Comment by abelsonlive** [comment]
I'm going to close this since im handling the broader issue in migration.

**Comment by mhkeller** [comment]
sounds good

On Thu, Aug 27, 2015 at 10:38 PM, Brian Abelson notifications@github.com
wrote:

> I'm going to close this since im handling the broader issue in migration.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newslynx/opportunities/issues/97#issuecomment-135616192
> .

## 

@mhkeller
mhkeller.com
